server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: sso-service
          uri: lb://sso-service
          predicates:
            - Path=/sso-service/**
          filters:
            - RewritePath=/sso-service/(?<path>.*), /$\{path}
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/news-service/**
          filters:
            - RewritePath=/news-service/(?<path>.*), /$\{path}
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact-service/**
          filters:
            - RewritePath=/contact-service/(?<path>.*), /$\{path}
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document-service/**
          filters:
            - RewritePath=/document-service/(?<path>.*), /$\{path}
        - id: announcement-service
          uri: lb://announcement-service
          predicates:
            - Path=/announcement-service/**
          filters:
            - RewritePath=/announcement-service/(?<path>.*), /$\{path}
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/support-service/**
          filters:
            - RewritePath=/support-service/(?<path>.*), /$\{path}
        - id: file-storage-service
          uri: lb://file-storage-service
          predicates:
            - Path=/file-storage-service/**
          filters:
            - RewritePath=/file-storage-service/(?<path>.*), /$\{path}
        - id: form-service
          uri: lb://form-service
          predicates:
            - Path=/form-service/**
          filters:
            - RewritePath=/form-service/(?<path>.*), /$\{path}
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing-service/**
          filters:
            - RewritePath=/billing-service/(?<path>.*), /$\{path}
        - id: iot-service
          uri: http://iot-service:8080
          predicates:
            - Path=/iot-service/**
          filters:
            - RewritePath=/iot-service/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
